### ISSUE TITLE
NA values for parquet data collection

### ISSUE THREAD

**Issue by keleighRey** [BWAM/bwam_analytics#5]
I found some blank rows for the result table using the code below, accessing the parquet file. `# All stream results from 2022 on
stream_df <- open_dataset(obt_dir) |> 
  filter(WATERBODY_TYPE %in% "river_stream",
         EVENT_DATETIME > as.POSIXct("2022-01-01 12:00:00"))|> 
  select(SITE_CODE,
         EVENT_ID,
         EVENT_DATETIME,
         PROJECT,
         FRACTION,
         PARAMETER_NAME,
         RESULT_VALUE,
         UNIT,
         RESULT_QUALIFIER) |> 
  distinct() |> 
  collect()
`

This is the code i used, and there are 2022 and 2023 sites that have an event and a project but no results.

**Comment by zsmith27** [comment]
All of these rows are associated with the SAMPLE_TYPE, "macroinvertebrate_abundance", which is not included in this table by design.

When I create this parquet file, I need to filter out SAMPLE_TYPE = "macroinvertebrate_abundance".

**Comment by zsmith27** [comment]
@keleighRey, a temporary fix would be to add `!SAMPLE_TYPE %in% "macroinvertebrate_abundance"` to your filter.

**Comment by zsmith27** [comment]
I updated the query to exclude "macroinvertebrate_abundance" rows during the parquet file generation. Included in the "generate_parquet_files.qmd" portion of this commit: https://github.com/BWAM/bwam_analytics/commit/16d9f9ecf31075d237b97417ef2aa4730275091a

**Comment by zsmith27** [comment]
I moved the location of the parquet file to here: L:\DOW\BWAM Share\data\parquet\analytical_table_store\obt_result.parquet.

See the following page for updated instructions: https://bwam.github.io/bwam_analytics/analytical_data_store.html
