### ISSUE TITLE
Request for mayfly and caddisfly occurrence data

### ISSUE THREAD

**Issue by zsmith27** [BWAM/bwam_analytics#8]
See email with subject: "Northeastern mayfly and caddisfly conservation status ranking"

**Comment by zsmith27** [comment]
@keleighRey , please review the linked script: https://github.com/BWAM/bwam_analytics/blob/main/queries/nhp_mayfly-caddisfly_spp-occurance.R

You should clone the repo as you normally do for a new project. Then you can try the code out.

**Comment by keleighRey** [comment]
@zsmith27  This looks good to me, I checked that sites/dates are not repeated and that there are no NA's in the dataset for the locational information and the species.   One thing of note - there are lake locations in here too, which I think is great, they didn't specify that they wanted either one. So maybe just point out that there are both types when it's sent on. Nice work! This is great to work with such nice clean data :)

**Comment by zsmith27** [comment]
Emailed data to the recipient on 8/23/2024.
